## 넘파이 개념
- Numerical Python의 약자
- 파이썬에서 배열을 처리할 때 널리 사용되는 유용하고 필수적인 라이브러리
- 특히 배열 계산에 최적화된 방식과 빠른 처리 속도를 자랑함

## 넘파이 특징
- 처리 속도가 빠름
- 유연한 연산 제공
- 배열의 내용을 한번에 디스크에 저장하고, 다시 불러오는 기능을 제공

### _는 왜 쓰는 걸까?

반복은 해야 하지만 반복 변수(i, j)를 전혀 사용하지 않을 때 관례적으로 _를 사용

In [3]:
# 정수를 저장하기 위해 5x5 크기의 랜덤 값으로 초기화된 2차원 리스트를 만들고, 리스트의 모든 값에 100을 더하는 코드

import random

# 파이썬 2차원 리스트 생성
SIZE = 5
pythonList = [[random.randint(0, 255) for _ in range(SIZE)] for _ in range(SIZE)]

for i in range(SIZE) :
    for k in range(SIZE) :
        print("%3d" % pythonList[i][k], end=' ')
    print()
print()

# 리스트에 100을 더하기
for i in range(SIZE) :
    for k in range(SIZE) :
        pythonList[i][k] += 100

# 리스트를 출력하기
for i in range(SIZE) :
    for k in range(SIZE) :
        print("%3d" % pythonList[i][k], end=' ')
    print()
print()


166 235  38 219 249 
231  34  72 168 230 
 72 110  99 171  42 
245 241 232  64 214 
187 239 230  13  47 

266 335 138 319 349 
331 134 172 268 330 
172 210 199 271 142 
345 341 332 164 314 
287 339 330 113 147 



넘파이 사용 버전

In [5]:
import numpy as np

SIZE = 5
numpyAry = np.random.randint(0, 255, size=(SIZE, SIZE))

print(numpyAry)
print()

numpyAry += 100

print(numpyAry)

[[102   6 226  32 228]
 [138  15  93 198 154]
 [ 55  58 110  83  26]
 [204 245 226 218 119]
 [112  20 213 246 156]]

[[202 106 326 132 328]
 [238 115 193 298 254]
 [155 158 210 183 126]
 [304 345 326 318 219]
 [212 120 313 346 256]]


## 넘파이 배열

### 자주 사용하는 배열 생성 함수

| 함수 | 설명 | 예시 |
|------|------|------|
| `np.array()` | 파이썬 리스트를 넘파이 배열(`ndarray`)로 변환한다. | `np.array([1, 2, 3])` |
| `np.arange()` | 일정한 간격의 값을 가지는 배열을 생성한다. (`range()`와 유사) | `np.arange(1, 6)` |
| `np.ones()` | 모든 원소가 1인 배열을 생성한다. | `np.ones((2, 3))` |
| `np.zeros()` | 모든 원소가 0인 배열을 생성한다. | `np.zeros((2, 3))` |
| `np.empty()` | 초기화하지 않은 배열을 생성한다. (쓰레기 값 포함 가능) | `np.empty((2, 3))` |
| `np.full()` | 지정한 값으로 모든 원소를 채운 배열을 생성한다. | `np.full((2, 3), 7)` |
| `np.identity()` | 대각선은 1, 나머지는 0인 단위 행렬을 생성한다. | `np.identity(3)` |
| `np.random.randint()` | 지정한 범위의 정수 난수 배열을 생성한다. | `np.random.randint(1, 10, (2, 3))` |
| `np.random.rand()` | 0 이상 1 미만의 실수 난수 배열을 생성한다. | `np.random.rand(2, 3)` |

### 예제

```python
import numpy as np

# 리스트 → 넘파이 배열
arr1 = np.array([1, 2, 3])

# 1부터 5까지
arr2 = np.arange(1, 6)

# 1로 채워진 배열
arr3 = np.ones((2, 3))

# 0으로 채워진 배열
arr4 = np.zeros((2, 3))

# 초기화되지 않은 배열
arr5 = np.empty((2, 3))

# 7로 채워진 배열
arr6 = np.full((2, 3), 7)

# 단위 행렬
arr7 = np.identity(3)

# 정수 난수 배열
arr8 = np.random.randint(1, 10, (2, 3))

# 실수 난수 배열
arr9 = np.random.rand(2, 3)
```

## 넘파이 데이터 형식
- 파이썬 리스트와 달리 넘파이 배열은 데이터 형식을 지정
- 넘파이의 데이터 형식을 dtype으로 표현하는데 정수, 실수, 불리언, 복소수, 문자열 등 다양한 형식이 지원됨
- 정수형도 8bit, 16bit, 32bit, 64bit 등을 지원하는데, int8, int16, int32, int64 등으로 부름
- 부호가 없는 정수형도 지원하는데, 앞에 u를 붙이면 됨
- 넘파이 배열을 생성하면서 데이터 형식(dtype)을 지정할 수 있음
- 이미 지정된 데이터 형식을 astype() 함수로 변경할 수도 있음